animals_list = [
    'Aves',
    'Bovinae',
    'Canidae',
    'Equidae',
    'Felidae',
    'Suidae',
    'Procyonidae',
    'Viverridae',
    'Mustelidae',
    'Leporidae',
    'Osteichthyes',
    'Aardvark',
    'Albatross',
    'Alligator',
    'Alpaca',
    'Anole',
    'Ant',
    'Anteater',
    'Antelope',
    'Ape',
    'Armadillo',
    'donkey',
    'Baboon',
    'Badger',
    'Barracuda',
    'Bat',
    'Bear ',
    'Beaver',
    'Bee',
    'Binturong',
    'Bird',
    'Bison',
    'Bluebird',
    'Boar',
    'Bobcat',
    'Budgerigar ',
    'Buffalo',
    'Butterfly',
    'Camel',
    'Capybara',
    'Caracal',
    'Caribou',
    'Cassowary',
    'Cat ',
    'Caterpillar',
    'Cattle',
    'Chamois',
    'Cheetah',
    'Chicken ',
    'Chimpanzee',
    'Chinchilla',
    'Chough',
    'Coati',
    'Cobra',
    'Cockroach',
    'Cod',
    'Cormorant',
    'Cougar',
    'Coyote',
    'Crab',
    'Crane',
    'Cricket',
    'Crocodile',
    'Crow',
    'Cuckoo',
    'Curlew',
    'Deer',
    'Dhole',
    'Dingo',
    'Dinosaur ',
    'Dog ',
    'DogfishAlso',
    'Dolphin',
    'Donkey',
    'Dove',
    'Dragonfly',
    'Duck',
    'Dugong',
    'Dunlin',
    'Eagle',
    'Echidna',
    'Eel',
    'Eland',
    'Elephant',
    'Elephant seal',
    'Elk',
    'Emu',
    'Falcon',
    'Ferret',
    'Finch',
    'Fish ',
    'Fisher',
    'Flamingo',
    'Fly',
    'Flycatcher',
    'Fox',
    'Frog',
    'Gaur',
    'Gazelle',
    'Gecko',
    'Genet',
    'Gerbil',
    'Giant panda',
    'Giraffe',
    'Gnat',
    'Gnu',
    'Goat ',
    'Goldfinch',
    'Goosander',
    'Goose',
    'Gorilla',
    'Goshawk',
    'Grasshopper',
    'Grouse',
    'Guanaco',
    'Guinea fowl',
    'Guinea pig',
    'Gull',
    'Hamster',
    'Hare',
    'Hawk',
    'Hedgehog',
    'Hermit crab',
    'Heron',
    'Herring',
    'Hippopotamus',
    'Hoatzin',
    'Hoopoe',
    'Hornet',
    'Horse ',
    'Human',
    'Hummingbird',
    'Hyena',
    'Ibex',
    'Ibis',
    'Iguana',
    'Impala',
    'Jackal',
    'Jaguar',
    'Jay',
    'Jellyfish',
    'Jerboa',
    'Kangaroo',
    'Kingbird',
    'Kingfisher',
    'Kinkajou',
    'Kite',
    'Koala',
    'Komodo dragon',
    'Kookaburra',
    'Kouprey',
    'Kudu',
    'Langur',
    'Lapwing',
    'Lark',
    'Lechwe',
    'Lemur',
    'Leopard',
    'Lion',
    'Lizard',
    'Llama',
    'Lobster',
    'Locust ',
    'Loris',
    'Louse',
    'Lynx',
    'Lyrebird',
    'Macaque',
    'Macaw',
    'Magpie',
    'MallardAlso see Duck',
    'Mammoth',
    'Manatee',
    'Mandrill',
    'Marmoset',
    'Marmot',
    'Meerkat',
    'Mink',
    'Mole',
    'Mongoose',
    'Monkey',
    'Moose',
    'Mosquito',
    'Mouse',
    'Myna',
    'Narwhal',
    'Newt',
    'Nightingale',
    'Nilgai',
    'Ocelot',
    'Octopus',
    'Okapi',
    'Opossum',
    'Orangutan',
    'Oryx',
    'Ostrich',
    'Otter',
    'Ox See Cattle',
    'Owl',
    'Oyster',
    'Panther',
    'Parrot',
    'Panda- See Giant panda',
    'Partridge',
    'Peafowl',
    'Penguin',
    'Pheasant',
    'Pig  Also see Boar',
    'Pigeon ',
    'Pika',
    'Polar bear',
    'Pony- See Horse',
    'Porcupine',
    'Porpoise',
    'Prairie dog',
    'Pug',
    'Quail',
    'Quelea',
    'Quetzal',
    'Rabbit ',
    'Raccoon',
    'RamAlso see Sheep',
    'Rat ',
    'Raven',
    'Red deer',
    'Red panda',
    'Reindeer',
    'Rhinoceros',
    'Rook',
    'Saki',
    'Salamander',
    'Salmon',
    'Sand dollar',
    'Sandpiper',
    'Sardine',
    'Sassaby',
    'Sea lion',
    'Seahorse',
    'Seal',
    'Serval',
    'Shark',
    'Sheep  Also see Ram',
    'Shrew',
    'Shrike',
    'Siamang',
    'Skink',
    'Skipper',
    'Skunk',
    'Sloth',
    'Snail',
    'Snake  ',
    'Spider  ',
    'Spoonbill',
    'Squid',
    'Squirrel',
    'Starling',
    'Stilt',
    'Swan',
    'Tamarin',
    'Tapir',
    'Tarsier',
    'Termite',
    'Thrush',
    'Tiger',
    'Toad',
    'Topi',
    'Toucan',
    'Turaco',
    'Turkey ',
    'Turtle',
    'Umbrellabird',
    'Vicuña',
    'Vinegaroon',
    'Viper',
    'Vulture',
    'Wallaby',
    'Walrus',
    'Wasp',
    'Water buffalo',
    'Waxwing',
    'Weasel',
    'Whale',
    'Wobbegong',
    'Wolf',
    'Wolverine',
    'Wombat',
    'Woodpecker',
    'Worm',
    'Wren',
    'tetra',
    'Yak',
    'Zebra']